# Generated by Django 4.2.4 on 2023-08-25 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('meal', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    'meal_type',
                    models.CharField(
                        choices=[
                            ('starters', 'Starters'),
                            ('salads', 'Salads'),
                            ('main_dishes', 'Main Dishes'),
                            ('desserts', 'Desserts'),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    'status',
                    models.IntegerField(
                        choices=[(0, 'Unavailable'), (1, 'Available')], default=1
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'chef',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
