# Generated by Django 4.2.4 on 2023-08-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='meal_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='meal',
            new_name='item',
        ),
    ]
