# Generated by Django 4.2.4 on 2023-08-26 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menu_price_currency_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
